// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhtfgcgbjldyakpkibhy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJodGZnY2diamxkeWFrcGtpYmh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4Nzc2NjQsImV4cCI6MjA2MzQ1MzY2NH0.BzScD-PzKE4fHhxL2G_5xBufIR_HJuGIp62Qbd96HbU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);